#!/bin/bash
if [ "$#" -ne 1 ]; then
    echo "Illegal number of parameters"
    exit 1
fi

mkdir src/$1
cp cpp.tpl src/$1/$1.cpp
sed "s/{PN}/$1/g" Makefile.tpl > src/$1/Makefile
sed "s/{PN}/$1/g" solution.md.tpl > src/$1/solution.md
cd src/$1